# Prometheus設定ファイル
# Studixアプリケーションの監視設定

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# ルールファイル
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# スクレイプ設定
scrape_configs:
  # Prometheus自身の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Studixアプリケーションの監視
  - job_name: 'studix-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/v1/health/detailed'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Nginxの監視
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Redisの監視
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

# アラート設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# ルール設定
rule_files:
  # - "alert_rules.yml"
